/*
 (c) Skimlinks 2009-2022
 Build time: Wed, 04 May 2022 13:45:55 GMT
 Version: "15.2.4-stackpath"
*/
(function(){function Zc(a){function b(a,b){if(!(!a.parentNode||va(a,e)||a.meta&&a.meta.ReadOnly)){var c=$c(a,b)[0];v(c,function(a){!f[a]&&ad(a)&&(f[a]=!0,r.domain_data.domains.push(a))})}}var c=x.get_as_hash_node_dict(),d=Object.keys(c).length;if(d){var e=Ra(bd.concat(Fb())),f={},l=Sa(function(a){R(a)}),k=0;v(c,function(c,e){window.setTimeout(function(){try{b(c,e)}catch(Eb){l(Eb)}finally{k+=1,k===d&&a(Object.keys(f))}},0)})}else a([])}function cd(a){var b;var c=b=null;var d=5;a.Limit&&(d=a.Limit);
var e=function(){return a.Priority||0};return{group_id:function(){return b?b.id():0},dec_limit:function(){return d-1},limit:function(){return d},action_type:function(){return a.ActionType},text:function(){return a.OriginalPhrase},start_byte:function(){return a.StartByte},url:function(){return a.Url},multi:function(){return a.Mt?!0:!1},group_priority:function(){return b?b.group_priority():e()},id:function(){return c?c:a.PhraseId},groups:function(){var b;return(b=a.Groups)?b:[]},title:function(){return a.Unlinked?
"":null!=a.ActionTitle?a.ActionTitle:"Shopping link provided by SkimWords"},set_title:function(b){a.Title=a.Unlinked?"":b},occurrence:function(){return a.PhraseOccurrence},set_group:function(a){return b=a},set_id:function(a){return c=a}}}function dd(){var a=w.linksImpressions;a={phr:a.skimwords.urls,unl:a.unlinked.urls,slc:a.skimlinks.count,swc:a.skimwords.count,ulc:a.unlinked.count,jsl:(new Date).getTime()-w.loading_started,pref:n.referrer,uc:wa,t:1,jsf:"",jv:fa};ha&&(a.xrf=1);return Gb(a)}function Hb(a,
b){var c=a.style.cssText;""!==c&&(c+=" ");var d=g("link_background");d&&(-1===d.indexOf("#")&&(d="#"+d),c+="background-color: "+d+" !important; ");null!==g("link_tooltip",null)&&(a.title=g("link_tooltip"));b&&(Ta&&(d=Ta,-1===d.indexOf("#")&&(d="#"+d),c+="color: "+d+" !important; "),Ua&&(c+="font-weight: "+Ua+" !important; "),ia&&(c="double"===ia?c+"border-bottom: 1px double !important; ":"dashed"===ia?c+"border-bottom: 1px dashed !important; ":c+("text-decoration: "+ia+" !important; ")),Va&&(c+="font-style: "+
Va+" !important; "),g("skimwords_link_style")&&(d=g("skimwords_link_style"),c+=d+"; "),g("skimwords_link_class")&&(a.className=F(a.className+" "+g("skimwords_link_class"))),Wa&&(a.title=Wa),null===a.getAttribute("title")&&(a.title="Shopping link added by SkimWords"),a.getAttribute("data-skim-creative")&&(d=parseInt(a.getAttribute("data-skim-creative"),10)%10,1===d||2===d))&&(a.title="");a.style.cssText=c;return!0}function Xa(a,b){b=b||Ib(a);if(!b)return!0;Jb(b);var c=g("skimlinks_keywee_pixel",null);
var d=q(p.location.href,"utm_campaign=fbkw");c&&d&&Kb(c);g("vglnk")&&S(b,"skimwords-link")&&(a&&a.stopPropagation?a.stopPropagation():(c=p.event,c.cancelBubble=!0));return!0}function Jb(a,b){a&&a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=Lb(a));if(a){var c=ed(a);var d=r.waypointDomain;if(c.length>=d.length&&c.substr(0,d.length)===d)return!0;if(-1!==c.indexOf(d))d=c;else{d=a;var e=S(d,"skimwords-link"),f=C(d,"data-skim-creative"),l=C(d,"data-skimlinks-tracking")||
wa,k=Ya?"&"+Ya:"";c=y(xa(),{id:Za,isjs:1,jv:fa,sref:p.location,url:c,xs:1,xtz:Mb(),xuuid:n.uuid});f&&(c.xcreo=f);n.isAdblockUser&&(c.abp=1);n.cookie&&(c.xguid=n.cookie);T&&(c.site=T);l&&(c.xcust=l);e&&(c.xs=2,c.xword=C(d,"data-skimwords-word")||"");e=H(d);e.icust&&(c.xjsf=e.icust);e.sourceApp&&(c.xs=e.sourceApp);e.clientClickId&&(c.cci=e.clientClickId,delete H(d).clientClickId);e.linkSwappingMatchId&&(c.ls=e.linkSwappingMatchId);d=r.waypointDomain+"/?"+U(c)+k}Nb(a,d,b)}return!0}function Lb(a){for(;a.parentNode;){a=
a.parentNode;var b=a.nodeName.toUpperCase();if("A"===b||"AREA"===b)return a}return null}function Ob(a,b,c){a=V(p,["skimlinks_settings",a],p[a]);return G(a)?b:u(c)?c(a,b):a}function g(a,b,c){if(W(a)){a:{void 0===a&&(a=[]);for(var d=0;d<a.length;d++){var e=Ob(a[d]);if(!G(e)){if(u(c)){b=c(e,b);break a}b=e;break a}}}return b}return Ob(a,b,c)}function Pb(){return V(ya(),["runTimeInfo","isAdblockUser"])}function ja(a){try{var b=a.skimlinksOriginalHref||a.href;return F(Qb(b)?b.baseVal:b)}catch(c){return console.error("Unexpected href format"),
console.error(c),""}}function Rb(a){var b=document.createElement("a"),c={};b.href=a;if(a=b.search.substring(1))for(a=a.replace(/&amp;/g,"&").split("&"),b=0;b<a.length;b++){var d=a[b].split("="),e=d[1];c[d[0]]=e?decodeURIComponent(e):null}return c}function za(a){return a?a.replace(/^www\./i,""):""}function $a(){for(var a="",b=0;8>b;b++)a+=Math.floor(65536*(1+Math.random())).toString(16).substring(1);return a}function u(a){return"[object Function]"===Object.prototype.toString.call(a)}function J(a,b,
c){for(var d=0,e=null===a?0:a.length;d<e;)c=b(c,a[d],d,a),d+=1;return c}function Aa(a){return"console"in window&&u(window.console[a])?window.console[a]:function(){}}function Ba(a,b){return J(b,function(b,d){return b&&u(a[d])},!0)}function fd(){try{var a=JSON.stringify({a:1});return 1===JSON.parse(a).a}catch(b){return!1}}function A(a,b){var c=Error(b);c.name=a;Sb(c,"getPrototypeOf"in Object?Object.getPrototypeOf(this):this.__proto__);Error.captureStackTrace&&Error.captureStackTrace(c,A);return c}function Sb(a,
b){"setPrototypeOf"in Object?Object.setPrototypeOf(a,b):a.__proto__=b}function G(a){return"undefined"===typeof a||null===a}function W(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)}function K(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function v(a,b){if(W(a))for(var c=0;c<a.length;c++)b(a[c],c,a);else for(c in a)K(a,c)&&b(a[c],c,a)}function y(){var a=arguments[0],b=Array.prototype.slice.call(arguments,1);G(a)&&(a={});v(b,function(b){G(b)&&
(b={});v(Object.keys(b),function(c){a[c]=b[c]})});return a}function ka(a,b){var c=[];v(a,function(d,e){b(d,e,a)&&c.push(d)});return c}function Tb(a){void 0===a&&(a=[]);return ka(a,function(a){return!!a})}function ab(a,b){if(!a)return[];if(!b)return[].concat(a);var c=[];v(a,function(d,e){c.push(b(d,e,a))});return c}function F(a){return G(a)?"":a.toString().replace(/^[\s\xA0]+|[\s\xA0]+$/g,"")}function Ca(a){return"boolean"===typeof a}function Q(a,b){return"undefined"===typeof a?b:a}function bb(a,b,
c){a=Q(a,"");b=Q(b,"");c=Q(c,0);return 0===a.slice(c).indexOf(b)}function Da(a,b,c){a=Q(a,"");b=Q(b,"");c=Q(c,0);c=c<a.length?c|0:a.length;return a.substr(c-b.length,b.length)===b}function Qb(a){var b=typeof a;return null!==a&&("object"===b||"function"===b)}function Ub(a){return encodeURIComponent(a).replace(/[!'()*~]/g,function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function B(a,b){void 0===b&&(b=!0);var c=document.createElement("a");if(b)var d=a;else{d=void 0;void 0===d&&(d="http");
var e="";/^https?:\/\//.test(a)||/^\/[^/]+/.test(a)||(e=/^\/\//.test(a)?d+":":d+"://");d=""+e+a}c.href=d;try{return za(c.hostname)}catch(f){return""}}function U(a,b){var c=[];b=b||Ub;v(a,function(a,e){c.push(e+"="+b(a))});return c.join("&")}function cb(a,b,c,d){function e(){if(u(d.onError)){var b=400<=h.status&&500>h.status,c=500<=h.status&&600>h.status;d.onError(new (0===h.status?gd:b?hd:c?id:jd)(k+" "+a+" "+h.status))}}b=b||{};d=d||{};var f=d.data,l=d.headers||{},k=d.method||"GET",h=new XMLHttpRequest;
d.withCredentials&&(h.withCredentials=!0);b=U(b);b.length&&(a=a+"?"+b);h.open(k,a);v(l,function(a,b){h.setRequestHeader(b,a)});h.onload=function(){if(u(c))if(200<=h.status&&300>h.status){try{var a=JSON.parse(h.responseText)}catch(Eb){a=h.responseText}c(a)}else e()};h.onerror=e;h.send(f);return h}function V(a,b,c){if(!a||!b||!b.length)return c;for(var d=b.length,e=0;e<d;e++){var f=b[e];if(a&&f in a)a=a[f];else return c}return a}function ya(){return window.__SKIM_JS_GLOBAL__&&u(window.__SKIM_JS_GLOBAL__.getDebugInfo)?
window.__SKIM_JS_GLOBAL__.getDebugInfo():{}}function kd(a){var b=/(?::(\d+))?:(\d+)$/,c=/^([^ ]+)\s\((.*)\)$/,d={filename:a,"function":"?",lineno:null,colno:null,in_app:!0};c.test(a)&&(a=a.match(c).slice(1),c=a[1],d["function"]=a[0],d.filename=c);b.test(d.filename)&&(c=d.filename.match(b).slice(1),a=c[0],c=c[1],a&&c?(d.lineno=parseInt(a,10),d.colno=parseInt(c,10)):!a&&c&&(d.lineno=parseInt(c,10)),d.filename=d.filename.replace(b,""));return d}function ld(a){a=a.stack.replace(a.toString(),"").replace(/^\s+at\s+/gm,
"").split("\n");a=ab(a,function(a){return F(a)});a=Tb(a);a.reverse();return ab(a,kd)}function R(a,b){if(a&&Vb){Wb.push(a);try{md.sendError(a,b)}catch(d){if(d===a)Xb.error(a);else{var c=new nd;c.__sentryExtraData__={logger_error_message:d.message,logger_error_stack:d.stack,initial_error_message:a.message,intial_error_stack:a.stack};throw c;}}}}function D(a){return u(a)?function(){try{a.apply(this,arguments)}catch(b){R(b)}}:a}function Sa(a){var b=!1,c;return function(){if(b)return c;c=a.apply(this,
arguments);b=!0;return c}}function Yb(a,b){return W(a)?a:b}function C(a,b,c){3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);try{var d=a[b];d||(d=a.getAttribute(b));return d}catch(e){return null}}function L(a,b){var c=Array.prototype.slice.call(arguments,2),d=D(a);return window.setTimeout.apply(window,[d,b].concat(c))}function od(a,b){function c(){"object"===typeof a.skimlinksOriginalHref?(a.href.baseVal=a.skimlinksOriginalHref.baseVal,a.href.animVal=a.skimlinksOriginalHref.animVal):
a.href=a.skimlinksOriginalHref;delete a.skimlinksOriginalHostname;delete a.skimlinksOriginalHref;delete a.skimlinksRestoreSwappedLink}b=b||Zb;var d=L(c,b);a.skimlinksOriginalHostname=a.hostname;a.skimlinksOriginalHref="object"===typeof a.href?{animVal:a.href.animVal,baseVal:a.href.baseVal}:a.href;a.skimlinksRestoreSwappedLink=function(){clearTimeout(d);c()}}function Nb(a,b,c){if(a){"string"===typeof a.skimlinksOriginalHref||od(a,c);c=null;var d=a.childNodes.length&&3===a.childNodes[0].nodeType;"msie"===
n.detect.browser&&d&&(c=a.innerHTML);"object"===typeof a.href?(a.href.baseVal=b,a.href.animVal=b):a.href=b;c&&c!==a.innerHTML&&(a.innerHTML=c)}}function $b(a){var b=a.href;b=n.cookie?b.replace(/([&?])xguid=([a-fA-F0-9]{32})/,"$1xguid="+n.cookie):b.replace(/([&?]xguid=[a-fA-F0-9]{32})/,"");b!==a.href&&Nb(a,b);return b}function ac(a){a=a||document;a=a.body||a.getElementsByTagName("body")[0];if(!a)throw new bc;return a}function Kb(a,b,c){if(!M){M=document.createElement("iframe");M.id="skimlinks-pixels-iframe";
try{ac().appendChild(M)}catch(f){f instanceof bc&&document.documentElement.appendChild(M)}var d=M;d.width=0;d.height=0;d.style.display="none"}var e=M.contentDocument||M.contentWindow.document;d=ac(e);d||(d=document.createElement("body"),e.appendChild(d));e=e.createElement("img");e.src=a;e.width=1;e.height=1;u(b)&&(e.onload=D(b));u(c)&&(e.onerror=D(c));d.appendChild(e)}function xa(){var a={};db&&(a.dnt=db);cc&&(a.fdnt=1);return a}function Ea(a,b,c,d){var e=d||{};d=e.usePixel||!1;var f=e.useSendBeacon||
!1;e=e.callback||function(){};c=y({},c,xa());f?dc(a,b,c,e):d?ec(a,b,c,e):eb(a,b,c,e)}function dc(a,b,c,d){b=JSON.stringify(b);return navigator.sendBeacon&&(a=fb(a,c),navigator.sendBeacon(a,b))?(d&&d(),!0):!1}function ec(a,b,c,d){c=y({},c);c.rnd=Math.random();b&&(c.data=JSON.stringify(b));Kb(fb(a,c),d,d)}function eb(a,b,c,d){b=JSON.stringify(b);gb.post(fb(a,c),{},d,{headers:{"Content-type":"text/plain"},data:b,withCredentials:!0})}function fb(a,b){var c=U(b),d=""+pd+a;return c?d+"?"+c:d}function q(a,
b){return u(a.indexOf)?-1<a.indexOf(b):!1}function N(a){var b=za(X);return q(a,hb)||q(a,"go.redirectingat.com")||!!b&&q(a,b)}function fc(a){a=B(a);return N(a)}function m(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a}function Fa(){Fa=Object.assign||function(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(a[d]=c[d])}return a};return Fa.apply(this,arguments)}function qd(a,
b){a.prototype=Object.create(b.prototype);a.prototype.constructor=a;a.__proto__=b}function Y(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return a}function rd(a,b){if(!a)throw Error("[matchSelector] First argument needs to be an html element.");var c=window.Element.prototype;c=c.matches||c.msMatchesSelector||c.mozMatchesSelector||c.webkitMatchesSelector;if(u(c))try{return c.call(a,b)}catch(e){return!1}c=(a.document||a.ownerDocument).querySelectorAll(b);
for(var d=0;c[d]&&c[d]!==a;)d+=1;return!!c[d]}function va(a,b){var c=sd(a);if(!c||!W(b)||0===b.length)return!1;var d=b.map(function(a){return a+" *"}).concat(b).join(",");return rd(c,d)}function sd(a){for(;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.parentNode;return a}function gc(a,b){for(var c=0;c<a.length;c++)if(b(a[c]))return a[c]}function Z(a,b){if("function"!=typeof a||null!=b&&"function"!=typeof b)throw new TypeError("Expected a function");if(!Z.Cache)return a;var c=function e(){for(var c=arguments.length,
l=Array(c),k=0;k<c;k++)l[k]=arguments[k];c=b?b.apply(this,l):l[0];k=e.cache;if(k.has(c))return k.get(c);l=a.apply(this,l);e.cache=k.set(c,l)||k;return l};c.cache=new Z.Cache;return c}function hc(a,b){return!!gc(b,function(b){var c=bb("*"),e=Da("*"),f=b.replace(/\*/g,"");return c&&e?q(a,f):c?Da(a,f):e?bb(a,f):a===b})}function ib(a,b){return a&&a.length&&b?"undefined"!==typeof gc(a,b):!1}function td(a){return g("_merchantSettings")?ib(ud,function(b){return q(a,b)}):!1}function jb(a){if(!a||!a.href)return!0;
var b=ja(a);(b=!ic(b))||(b=[].concat(vd(),Fb(),jc),b=b.length&&va(a,b)?!0:kb.length?!va(a,kb):!1);return b}function ic(a){if(!a||td(a))return!1;var b=r.hostname;var c=Q(void 0,!0);c=B(a,c);var d=Da(c,"."+b)||Da(b,"."+c);if(b=c!==b&&!d)a=B(a),a=Ga.length?!hc(a,Ga):hc(a,wd()),b=!a;return b}function xd(a){var b;if(b=kc)null===a.offsetParent?b=!0:(b=p.getComputedStyle,b=u(b)?"hidden"===b(a).visibility:!1);if(b)return t.IGNORE;var c=ja(a);b=za(B(c));c=c?/^https?:\/\//.test(c)||/^\/\//.test(c):!1;if(c&&
!jb(a)){if(ha)return t.TRACK;if(!0===r.aff_domains[b]||K(lb,b))return t.AFFILIATE;if(N(b))return t.PRE_AFFILIATED;if(a=mb)a=!K(r.aff_domains,b)||G(r.aff_domains[b]);return a?t.UNKNOWN:""===n.cookie&&lc?t.AFFILIATE:t.TRACK}return t.IGNORE}function S(a,b){if(!a||!a.className||!b)return!1;var c=a&&a.className?F(a.className).split(/\s+/):[];return q(c,b)}function Ha(a){if("string"!==typeof a.skimlinksOriginalHref)return!1;var b=H(a),c=Rb(a.href);b.icust&&b.icust!==c.xjsf&&(c.xjsf=b.icust);b.sourceApp&&
b.sourceApp!==c.xs&&(c.xs=b.sourceApp);b=U(c);a.href=r.waypointDomain+"?"+b;return!0}function H(a){if(!a)throw Error("getAnchorMetaData takes an anchor HTML element as an argument");var b=V(a,[mc]);if(!b){b={icust:null,sourceApp:null};var c=[mc],d=b;if(a&&c&&c.length)for(var e=c.length,f=a,l=null,k=0;k<e;k++){var h=c[k];if(k===e-1){try{a[h]=d}catch(Ye){f[l]={},f[l][h]=d}break}h in a&&Qb(a[h])||(a[h]={});f=a;l=h;a=a[h]}}return b}function nc(a,b,c){b=y({},b,{domain_id:la,publisher_id:ma,page_url:p.location.href,
impression_id:n.uuid,jv:fa});var d={};navigator.sendBeacon?d.useSendBeacon=!!c:d.usePixel=!!c;Ea("/generic_tracking/"+a,b,{},d)}function Ib(a){a=a.target||a.srcElement||a.originalTarget;if(!a)return null;var b=(a.nodeName||"").toLowerCase();return q(["a","area"],b)?a:Lb(a)}function Ia(a){try{return a()}catch(b){}}function yd(a){var b=g("gtag");Ia(function(){b("event",aa,{event_category:"click",event_label:a})})}function zd(a){var b=g("ga");Ia(function(){b("send","event","click",aa,a)})}function Ad(a){var b=
g("_gaq");Ia(function(){b.push(["_trackEvent","click",aa,a])})}function Bd(a){var b=g("pageTracker");b._trackPageview&&Ia(function(){b._trackPageview("/"+aa+"/"+a)})}function Cd(a,b){return J(Object.keys(b),function(c,d){var e=a[d]===b[d];return c&&e},!0)}function oc(a){return J(a,function(a,c){return a.concat(c)},[])}function na(a,b){void 0===b&&(b=!0);var c=a?"."+a:"";return oc(E.querySelectorAll(b?"a[href]"+c+", area[href]"+c:"a[href]"+c))}function Dd(a,b){v(a,function(a){var c=q(b,a)&&!N(a);r.aff_domains[a]=
c})}function Ed(a,b){return!ib(a,function(a){return!b(a)})}function Fd(){for(var a=new I,b=arguments.length,c=Array(b),d=0;d<b;d++)c[d]=arguments[d];a.waitFor(c);return a}function Ra(a){return J(a,function(a,c){return q(a,c)?a:a.concat(c)},[])}function nb(a){var b=pc[a];if(!b)throw Error("Unknown service "+a);return b}function qc(a,b){if(a){var c=[].concat(a.split(" "),b);c=Ra(c)}else c=b;return c}function Gd(){if(ob||Ja){var a=[];ob&&a.push("nofollow");Ja&&(a=qc(Ja,a));v(na(),function(b){var c=a,
d=C(b,"rel"),e=za(b.hostname);e&&!0===r.aff_domains[e]&&C(b,"rel",qc(d,c).join(" "))})}}function Hd(a){if(a.affiliationType===t.IGNORE)return!1;var b=a.anchor,c=a.affiliationType,d=a.nativeEvent;if(a.type===ba.LEFT_CLICK)if(b=a.anchor,c=a.affiliationType,c===t.AFFILIATE||c===t.UNKNOWN){b=a.anchor;c=a.nativeEvent;d=a.clientClickId;var e,f,l;if(l=g("skimlinks_strip_attribute",!1))for(f in l)if(K(l,f)){var k=l[f];(e=C(b,f))&&0===e.indexOf(k)&&(e=e.substr(k.length),C(b,f,e))}oa&&C(b,"target",oa);H(a.anchor);
H(b).clientClickId=d;Ha(b);aa&&(a=b.href,g("gtag")?yd(a):g("ga")?zd(a):g("_gaq")?Ad(a):g("pageTracker")&&Bd(a));a=rc?(a=C(b,"onclick"))&&q(a.toString(),"return false")?!0:(a=b.onclick)&&u(a)&&q(a.toString(),".preventDefault()")?!0:!1:!1;a?(Xa(c,b),(oa?p.open(b.href,oa):p.open(b.href,"_blank")).focus()):Xa(c,b)}else c===t.PRE_AFFILIATED?$b(b):c===t.TRACK&&(a={publisher_id:ma,publisher_domain_id:la,referrer:p.location.toString(),pref:n.referrer,site:""+T,url:b.href,custom:C(b,"data-skimlinks-tracking")||
wa||"",xtz:n.timezone,uuid:n.uuid,product:"1"},ha&&(a.xrf=1),Ea("/naclicks",a,null,{usePixel:!0}));else{try{if(l=H(b),!l.icust||-1!==l.icust.indexOf("other_click__")){e="other_click__"+d.type+" ["+(void 0!=d.button?d.button:"")+"]";if(32<String(e).length)throw Error(e+" is not a valid icust value. The value should be less than 33 chars");H(b).icust=e;Ha(b)}}catch(h){}c===t.AFFILIATE||c===t.UNKNOWN?Jb(b,200):c===t.PRE_AFFILIATED&&$b(b)}return!0}function Id(){nb(ca.ANCHOR_CLICK_INTERCEPTOR).registerInterceptor(Hd,
pa.SKIMLINKS)}function Jd(){n.skimlinksEnabled&&(z.on("skim_js_start",Id),O.whenBeaconFullyReady(Gd))}function sc(a){var b;return a&&-1!==a.indexOf("class=")&&(b=a.match(/([^[]+)\[class=([^\]]+)\]/i))&&3===b.length?b[1]+"."+b[2]:a}function Kd(){var a=na();return J(a,function(a,c){var b=Ka;var e=ja(c);e=B(e);b&&N(e)&&(b=La.createFromUrl(c.href))&&(e=b.getTargetDomain());e=(b=e)&&!jb(c)&&!N(b);var f=K(r.aff_domains,b);e&&!f&&(a.push(b),r.aff_domains[b]=null,r.domain_data.domains.push(b));return a},
[])}function tc(a){var b=Kd();return O.sendBeaconRequest(b,a)}function uc(a,b){v(a,function(a){void 0===r.aff_domains[a]&&(r.aff_domains[a]=null)});O.sendBeaconRequest(a,da.AUX).readyState.whenReady(b)}function Gb(a){return y({pag:p.location.href,guid:n.cookie,uuid:n.uuid,tz:n.timezone,publisher_id:ma,publisher_domain_id:la},a)}function vc(a){if(0!==w.awaitedModules.length&&(w.awaitedModules=ka(w.awaitedModules,function(b){return b!==a}),0===w.awaitedModules.length)){var b=dd();Ea("/page",b)}}function Ld(a){a=
a.match.phrase;return{w:a.text(),lp:a.url(),t:Ma.creative}}function Md(a){a=a||[];var b=J(a,function(a,b,e){a[e]=b;return a},{});w.linksImpressions.unlinked={count:a.length,urls:b};vc("unlinked")}function pb(a){return String(a).replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function qb(a,b,c,d){void 0===d&&(d=!1);if(a&&(a.nodeName||a===p))if(E.addEventListener){var e=D(c.bind(a));a.addEventListener(b,e,d)}else a.attachEvent("on"+b,function(){return 7>n.detect.version&&
!p.event?(L(c.bind(a,p.event),100),!0):c.call(a,p.event)})}function wc(a,b){Xa(a,b)}function Nd(){p.__SKIM_JS_GLOBAL__.bundledEntries.unlinked=!0;if(n.unlinkedEnabled){if(n.skimwordsEnabled)z.on("instant_api_callback_settings",Od);else O.whenPostPageLoadBeaconCallCompleted(xc);z.on("dom_changed",yc)}}function rb(a){Pd.setReady();Md(a)}function Od(){var a=qa.settings;2===a.nc?n.unlinkedEnabled&&uc(r.domain_data.domains,zc):n.unlinkedEnabled&&(a.includes?(P&&P.length&&(a.excludes=a.excludes.concat(P)),
x.traverse(a.includes,a.excludes,a.read_onlys)):P&&P.length?x.traverse(["body"],P,[]):x.traverse(["body"],[],[]));xc()}function xc(){a:{var a=E.getElementsByTagName("body");if(a.length){a=a[0].textContent||a[0].innerText;var b;if(b=a)a=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^[\]\s]*\b|$/gi.exec(a),b=a.length&&""!==a[0]?!0:!1;if(b){a=!0;break a}}a=!1}a?(n.skimwordsEnabled||x.traverse([],P,[]),yc()):rb()}function yc(){Zc(function(a){a.length?uc(a,zc):rb()})}function zc(){var a=
[];Object.keys(r.aff_domains).length&&(v(Ma.url_spans,function(b){r.aff_domains[b.match.domain]&&(Qd(b.node,b.match,!0),a.push(Ld(b)))}),L(function(){var a;var c=na("skimlinks-unlinked");var d=[];var e=0;for(a=c.length;e<a;e++){var f=c[e];d.push(Rd(f))}return d},10));rb(a)}function Sd(a,b){var c=y({},Td,b||{}),d=document.createElement("script");d.src=a;d.type="text/javascript";d.async=c.async;d.onload=D(c.onLoad);d.onerror=D(function(){R(new Ud(a));c.onError()});document.head.appendChild(d);return d}
function Vd(){var a=!Ac;sb&&(!a||E.querySelector('[data-m101-skimlinks="true"]')||E.querySelector("[data-m101-type]")||E.querySelector("[data-type][data-config]"))&&Sd(Wd+"/widget/code/"+sb+".js")}function Xd(){return J(na(),function(a,b){var c=ja(b),d=B(c),e;(e=!d)||(e=!(!S(b,"skimwords-link")&&!S(b,"skimlinks-unlinked")));(e=e||!ic(c))||(e=b&&W(Na)&&0!==Na.length?va(b,Na):!1);if(e)return a;(e=a.urls[c])||(e={count:0,ae:!0===r.aff_domains[d]||(null===r.aff_domains[d]||void 0===r.aff_domains[d])&&
mb&&!N(d)?1:0});e.count++;a:{if(-1!==c.indexOf("#slm-")&&(d=c.split("#slm-"),2===d.length&&!isNaN(d[1])&&10*parseInt(d[1],10)===10*d[1])){d=parseInt(d[1],10);break a}d=null}d&&(e.slmcid=d);d=e;1===d.ae&&a.count++;d.slmcid&&(e=d.slmcid,q(w.campaign_ids,e)||w.campaign_ids.push(e));if(!Bc&&0===d.ae)return a;a.urls[c]=d;return a},{urls:{},count:0})}function Yd(){v(Zd,function(a){var b=p;"skimlinks_context_window"===a&&(b=window);K(b,a)&&(a={page_var:a,value:JSON.stringify(b[a])},nc("page_variable_tracking",
a))})}function $d(){var a=Sa(function(){w.linksImpressions.skimlinks=Xd();vc("main-tracking");if(Object.keys(w.linksImpressions.skimlinks.urls).length){var a=Gb({dl:w.linksImpressions.skimlinks.urls,hae:w.linksImpressions.skimlinks.count?1:0,typ:"l"});Ea("/link",a)}});O.whenNoRequestsPending(a);L(a,2E3)}function ae(){w.awaitedModules.push("main-tracking");n.skimwordsEnabled&&w.awaitedModules.push("skimwords");n.unlinkedEnabled&&w.awaitedModules.push("unlinked");Cc&&O.whenPostPageLoadBeaconCallCompleted($d);
if(navigator.sendBeacon&&1>1E4*Math.random()){var a={domain_id:la,publisher_id:ma,page_url:p.location.href,impression_id:n.uuid,jv:fa},b=dc("/generic_tracking/trackingMethodExperiment",y({trackingMethod:"sendBeacon"},a));eb("/generic_tracking/trackingMethodExperiment",y({trackingMethod:"xhr"},a));b||eb("/generic_tracking/trackingMethodExperiment",y({trackingMethod:"sendBeaconFailed"},a))}}function be(){Yd()}function ce(a,b){var c={headers:{"Content-type":"application/json"},data:JSON.stringify({publisher_id:ma,
publisher_domain_id:la,page_url:p.location.href,urls:a}),withCredentials:!0},d=xa();gb.post(""+de,d,b,c)}function Dc(a){var b=a.href;fc(b)&&(a=La.createFromUrl(a.href))&&(b=a.getTargetUrl());return b}function Ec(a,b){ea||1E3<b?u(a)&&(ea?tb?a(!0):a(!1):a(!1)):L(Ec,b*=2,a,b)}function Fc(){ea||(ra.complete&&sa.complete&&(ea=!0),ea&&"0"!=ra.width&&"0"==sa.width&&(tb=!0))}function ee(a){function b(a){return a.toLowerCase().replace(/^\/\/|^https?:\/\//,"")}var c=ab(Gc,b);return q(c,b(a))}function fe(){return{skimOptions:ge,
runTimeInfo:y({},{aff_domains:r.aff_domains},{consentState:he},{loggedErrors:Wb},n)}}function ie(a,b){var c=!1,d;return function(){if(c)return d;L(function(){c=!1},b);c=!0;return d=a.apply(this,arguments)}}function Hc(a,b,c,d){void 0===b&&(b=[]);if(a){var e=ie(c,200);v(b,function(b){try{qb(a,b,e,d)}catch(l){}})}}function je(){var a=new ke;pc[ca.ANCHOR_CLICK_INTERCEPTOR]=a}function le(){p.__SKIM_JS_GLOBAL__||(p.__SKIM_JS_GLOBAL__={});if(!p.__SKIM_JS_GLOBAL__.init){p.skimlinksAPI={};p.__SKIM_JS_GLOBAL__.init=
!0;p.__SKIM_JS_GLOBAL__.getDebugInfo=fe;p.__SKIM_JS_GLOBAL__.bundledEntries=me;if(ee(r.hostname)||ub&&E.querySelector(ub))n.skimlinksEnabled=!1,n.skimwordsEnabled=!1,n.unlinkedEnabled=!1;"msie"===n.detect.browser&&8>=n.detect.version&&(n.skimwordsEnabled=!1);try{ec("/robots.txt",void 0,{__skimjs_preflight__please_ignore__:!0})}catch(a){R(new ne,!0)}oe.detect(function(a){n.isAdblockUser=a});z.publish("skim_js_init");q(["interactive","complete"],E.readyState)?L(ta,0):(tc(da.PRE_PAGE_LOAD),document.addEventListener("DOMContentLoaded",
ta),document.addEventListener("load",ta));je();z.publish("skim_js_start")}}var Xb={log:Aa("log"),info:Aa("info"),warn:Aa("warn"),error:Aa("error")},Vb=function(){var a=!0;try{var b=[fd(),!!(window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest),Ba(document,["querySelector","querySelectorAll"]),Ba(Object,["keys"]),Ba([],["indexOf"]),Ba("",["indexOf"])];a=J(b,function(a,b){return a&&b},!0)}catch(c){a=!1}!1===a&&Xb.info("[Skimlinks] Your browser doesn't support the base features necessary to run our javascript.");
return a}();A.prototype=Object.create(Error.prototype,{constructor:{value:Error,enumerable:!1,writable:!0,configurable:!0}});Sb(A,Error);var bc=A.bind(null,"DocumentBodyNotFound"),pe=A.bind(null,"PixelDropFailed"),Ud=A.bind(null,"ScriptDropFailed"),jd=A.bind(null,"XhrError"),hd=A.bind(null,"XhrError4xx"),id=A.bind(null,"XhrError5xx"),gd=A.bind(null,"XhrErrorZero"),nd=A.bind(null,"SentryLoggerError");A.bind(null,"SendBeaconFailedError");var ne=A.bind(null,"ResolveSslCertificateError");A.bind(null,
"DisclosureReadyStateTimeout");var fa="15.2.4-stackpath",qe="https://r.skimresources.com/api/",lb={"t.umblr.com":{name:"z"}},Za="107033X1569419",ma=107033,la=1569419,pd="https://t.skimresources.com/api/v2",Wd="https://m.skimresources.com",de="https://ls.skimresources.com/api",hb="go.skimresources.com",re="https://sl-sentry.skimlinks.com",Ic="f648b8dfc7284fad8af093653eafd6ca",se="production",te=1>1E3*Math.random(),md=
{sendError:function(a,b){if(!Ic)throw a;var c=b;c=(c=Ca(c)?c:!1)||te?a instanceof pe&&Pb()?!1:!0:!1;if(c){c=re+"/api/46/store/";var d={sentry_version:"7",sentry_client:"raven-js/3.26.4",sentry_key:Ic};var e={country:V(ya(),["runTimeInfo","country"]),beacon_consent:V(ya(),["runTimeInfo","consent"]),iab_consent:V(ya(),["runTimeInfo","consentState","skimlinks_consent"]),is_adblock_user:Pb(),is_top_frame:window.top===window};e={event_id:$a(),project:"46",platform:"javascript",logger:"javascript",release:fa,
exception:{values:[{type:a.name,value:a.message,stacktrace:{frames:ld(a)}}]},request:{headers:{"User-Agent":navigator.userAgent},url:location.href},extra:y({original_stacktrace:a.stack},a.__sentryExtraData__,e)};cb(c,d,null,{method:"POST",data:JSON.stringify(e)})}}},Wb=[],Mb=Sa(function(){return(new Date).getTimezoneOffset()}),Jc=window.skimlinks_context_window||null,p=Jc?window[Jc]:window,E=p.document,ue={getItem:function(a){try{return JSON.parse(localStorage.getItem(a))}catch(b){return null}},
setItem:function(a,b){try{localStorage.setItem(a,JSON.stringify(b))}catch(c){}}},vb=g("noskim",!1),ve=g("noskimlinks",!1),we=g("noskimwords",!0),xe=g("nounlinked",!1),ye=g("skimwords_standard",false),ze=g("skimwords_lite",false),Ae=g("skimwords_diy",false),Be=g("skimwords_diy_filter",false),Kc=!vb&&!ve,Lc=!vb&&!we,Mc=!vb&&!xe,db=g("skimlinks_dnt",0,function(a){return a&&"0"!==a&&"false"!==
a?1:0}),cc=g("skimlinks_nocookie",!1),wb=g("skimlinks_excluded_classes",[]),jc=g("custom_excluded_selectors",[],Yb),kb=g("custom_included_selectors",[],Yb),xb=g("skimlinks_exclude",["booking.com","viator.com","hotelscombined.co.uk","hotelscombined.com","travelzoo.com","groupon.com","secretescapes.com","airbnb.co.uk","airbnb.com","redballoon.com.au","skyscanner.net","checkout.timeout.com","hilton.com","vinomofo.com","bloomeroo.com.au","flowerchimp.com"]),Ga=g("skimlinks_include",[]),kc=g("skimlinks_ignore_hidden_links",false),Na=g("skimlinks_link_impression_exclude_selector",
[]),ob=g("skimlinks_add_nofollow",false),Ja=g("skimlinks_custom_rel",""),Nc=g("skimlinks_before_click_handler",false,function(a,b){return Ca(a)?a:b}),lc=g("skimlinks_first_party_na",!1),Cc=!g("noimpressions",!1),Bc=false,Zb=g("skimlinks_replace_timeout",300,
function(a,b){var c=parseFloat(a);return isNaN(c)?b:c}),mb=g("skimlinks_affiliate_unknown_links",true),oa=g("skimlinks_target",null),Ce=g("skimlinks_ajax_rerun",false),P=[],ha=g("skimlinks_revenue_forecast",false),Oc=g("skimlinks_noright",false),Pc=g("skimlinks_url_extraction_rules",!1)||false,
Ya=g("skimlinks_extra_redir_params",[]).join("&"),wa=g(["affiliate_tracking","skimlinks_tracking"],!1),Oa=g("force_location"),T=g(["skimlinks_site","skimlinks_sitename"],!1),X=g("skimlinks_domain",""),aa=g("skimlinks_google",false,function(a,b){return a?Ca(a)?a?"skimout":"":F(a):b?"skimout":""}),Gc=g("noskim_domains",[]),De=g("skimwords_horizontal_distance",80),Ee=g("skimwords_vertical_distance",
80),Fe=false,Ta=g("skimwords_color",null),Ua=g("skimwords_weight",null),ia=g("skimwords_decoration",null),Va=g("skimwords_style",null),Wa=g("skimwords_title",null),ub=g("no_skim_selector",""),Ge=g("skimlinks_force_consent",!1),sb="107033X1582018",
Ac=false,rc=true,yb=g("link_swapping_404",!0),zb=g("link_swapping_product_match",!0),Ka=(yb||zb)&&g("link_swapping",!0),Qc=true,ge={SW_STANDARD:ye,SW_LITE:ze,SW_DIY:Ae,SW_DIY_FILTER:Be,HAS_SKIMLINKS:Kc,HAS_SKIMWORDS:Lc,HAS_UNLINKED:Mc,DO_NOT_TRACK:db,NO_COOKIE:cc,SL_EXCLUDED_CLASSES:wb,CUSTOM_EXCLUDED_SELECTORS:jc,CUSTOM_INCLUDED_SELECTORS:kb,SL_EXCLUDED_DOMAINS:xb,
SL_INCLUDED_DOMAINS:Ga,SL_IGNORE_HIDDEN_LINKS:kc,SL_IMPRESSION_EXCLUDED_SELECTORS:Na,SL_ADD_NOFOLLOW:ob,SL_CUSTOM_REL:Ja,SL_BEFORE_CLICK_HANDLER:Nc,SL_FIRST_PARTY_NA:lc,SL_TRACK_IMPRESSION:Cc,WITH_NA_LINK_IMPRESSIONS:Bc,SL_REPLACE_TIMEOUT:Zb,SL_AFFILIATE_UNKNOWN_LINKS:mb,SL_TARGET:oa,AJAX_SUPPORT:Ce,UNLINKED_EXCLUDES:P,SL_FORECAST:ha,NO_RIGHT_CLICK:Oc,USE_MERCHANT_URL_EXTRACTION_RULES:Pc,EXTRA_REDIR_PARAMS:Ya,CUSTOM_TRACKING_VAR:wa,FORCE_LOCATION:Oa,SITE_NAME:T,CUSTOM_WAYPOINT_DOMAIN:X,GOOGLE_TRACKING_ACTION_NAME:aa,
NO_SKIM_DOMAINS:Gc,SW_HORIZONTAL_DISTANCE:De,SW_VERTICAL_DISTANCE:Ee,SL_PROFILING:!1,TRACK_COOKIE_SYNCS:Fe,SW_LINK_COLOR:Ta,SW_LINK_WEIGHT:Ua,SW_LINK_DECORATION:ia,SW_LINK_STYLE:Va,SW_LINK_TITLE:Wa,NO_SKIM_SELECTOR:ub,SL_CONSENT:!1,FORCE_CONSENT:Ge,M101_TRACKING_ID:sb,M101_CUSTOM_DOM_DETECTION:Ac,AE_CLICK_TRACKING:!1,INCENTIVE_ENABLED:!1,FORCE_PREVENTED_CLICKS_MONETIZATION:rc,IS_MINIMALISTIC_JS:!1,LINK_SWAPPING_404:yb,LINK_SWAPPING_OUT_OF_STOCK:!1,LINK_SWAPPING_PRODUCT_MATCH:zb,LINK_SWAPPING:Ka,LINK_SWAPPING_MERCHANT_NAME_DETECTION:Qc},
n=function(){var a=E.referrer||document.referrer||"",b=Oa||p.location.href;var c="aspsession-id aspsessionid cftoken j-sessionid jsessid jsession_id jsessionid phpsessid phpsession-id phpsessionid seskey sessid session-id session-key session_id sessionid sessionkey uniqueid utm_campaign utm_medium utm_source utm_term".split(" ");for(var d=0;d<c.length;d++){var e=c[d];var f=b.split("?");if(2<=f.length){b=f.shift();f=f.join("?");e=encodeURIComponent(e)+"=";f=f.split(/[&;]/gi);for(var l=f.length-1;0<=
l;l--)bb(f[l],e)&&f.splice(l,1);b=b+"?"+f.join("&")}}"?"===b[b.length-1]&&(b=b.substr(0,b.length-1));c=b;d=ue.getItem("skimCONSENT");b=navigator.userAgent.toLowerCase();b=/(webkit)[ /]([\w.]+)/.exec(b)||/(opera)(?:.*version)?[ /]([\w.]+)/.exec(b)||/(msie) ([\w.]+)/.exec(b)||0>b.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(b)||[];b={browser:b[1]||"",version:parseFloat(b[2])||0};return{cookieSyncString:"",lastBeaconTimestamp:null,cookie:"",country:"",locale:"",consent:d,detect:b,isAdblockUser:!1,
pageLocation:c,referrer:a,timezone:Mb(),uuid:$a(),skimwordsEnabled:Lc,skimlinksEnabled:Kc,unlinkedEnabled:Mc}}(),r=function(){var a=document.getElementsByTagName("html")?document.getElementsByTagName("html")[0]:null,b=Oa?B(Oa,!1):p.location.hostname;return{aff_domains:{},beacon:[],domain_data:{domains:[]},exclude:xb,exclude_lookup:null,excluded_classes:["noskimlinks","noskim"].concat(wb),has_been_called:!1,hostname:b,html_root:a,include:Ga,include_lookup:null,links:[],links_tracked:!1,target:null,
waypointDomain:X?"http://"+X:"https://"+hb}}();var qa={};var Ma={creative:"500005",url_spans:[]};var Rc=function(a,b,c){if(0===b)return c;try{return a()}catch(d){return Rc(a,b-1,c)}};get_real_link=function(a){if(null==a)return null;for(;"A"!==a.nodeName.toUpperCase();)if(a=Rc(function(){return a.parentNode},3,null),null==a)return null;return a};var M,gb={get:function(a,b,c,d){d=y({onError:R},d,{method:"GET"});cb(a,b,D(c),d)},post:function(a,b,c,d){d=y({onError:R},d,{method:"POST"});cb(a,b,D(c),d)}},
He={waypointDomain:X||hb},La=function(){function a(a,c){var b=this;void 0===c&&(c=He);m(this,"waypointDomain",void 0);m(this,"waypointParams",void 0);m(this,"updateWaypointParams",function(a){if(K(a,"url")&&G(a.url))throw Error("[WaypointUrlObject][updateWaypointParams] 'url' param can not be null nor undefined");b.waypointParams=Fa({},b.waypointParams,{},a);b.cleanUpWaypointParamsAfterUpdate()});m(this,"getWaypointUrl",function(){var a=U(b.waypointParams);return""+b.getWaypointDomainProtocol()+b.waypointDomain+
"/?"+a});m(this,"getTargetUrl",function(){return b.waypointParams.url});m(this,"getTargetDomain",function(){return B(b.getTargetUrl())});m(this,"getWaypointDomainProtocol",function(){return b.waypointDomain===X?"http://":"https://"});m(this,"cleanUpWaypointParamsAfterUpdate",function(){v(b.waypointParams,function(a,c){G(a)&&delete b.waypointParams[c]});b.waypointParams=Fa({},b.getDefaultWaypointParams(),{},b.waypointParams)});if(null==a||!a.url)throw Error("[WaypointUrlObject][constructor] 'url' is mandatory");
this.waypointDomain=c.waypointDomain;this.updateWaypointParams(a)}a.prototype.getDefaultWaypointParams=function(){var a={id:Za,sref:p.location.href,xs:1};n.cookie&&(a.xguid=n.cookie);return a};a.createFromUrl=function(b){var c=B(b);if(!N(c))return null;try{var d=Rb(b);return d.url?new a(d,{waypointDomain:c}):null}catch(e){return null}};return a}();"undefined"!==typeof window.Map&&(Z.Cache=Map);var Ie=["noskim","norewrite"],Je=["noskimlinks","noskim"].concat(["taboola","advert--taboola","trc_rbox",
"trc_related_container"]),Ke="*.criteo.com *.g.doubleclick.net *mjxads.internet.com *overture.com *pgpartner.co.uk *pgpartner.com *pricegrabber.co.uk *pricegrabber.com *youtube.com m.skimresources.com paid.outbrain.com track.celtra.com traffic.outbrain.com trc.taboola.com zergnet.com ad.doubleclick.net".split(" "),ud=["itunes.apple.com","itunes.com","phobos.apple.com"],wd=Z(function(){var a=[].concat(xb,Ke);T&&a.push(T);return a}),Fb=Z(function(){return Je.concat(wb).map(function(a){return"."+a})}),
vd=Z(function(){return Ie.map(function(a){return"a[rel~='"+a+"']"})}),Le=function(){var a=/[-[\]{}()*+?.,\\^$|#]/g,b=/\s+/g;return function(c){return c.replace(a,"\\$&").replace(b,"\\s+")}}(),t;(function(a){a.AFFILIATE="AFFILIATE";a.PRE_AFFILIATED="PRE_AFFILIATED";a.UNKNOWN="UNKNOWN";a.TRACK="TRACK";a.IGNORE="IGNORE"})(t||(t={}));var mc="__skimlinks__";var ed=function(a){a=ja(a);if(Pc){var b=B(a);if(b in lb)return b="[&?]"+lb[b].name+"=(http[^&]+)",b=new RegExp(b),decodeURIComponent(null!=a?a.match(b).pop():
void 0)||a}return a};var Sc;(function(a){a.STARTING="STARTING";a.CANCELLED="CANCELLED";a.PENDING_API="PENDING_API";a.API_ERROR="API_ERROR";a.NO_OFFERS="NO_OFFERS";a.PENDING_MODULE="PENDING_MODULE";a.READY="READY"})(Sc||(Sc={}));var z={topics:{},on:function(a,b,c){W(this.topics[a])||(this.topics[a]=[]);var d;c&&(d=function(a){Cd(a,c)&&b(a)});this.topics[a].push(d||b)},publish:function(a,b){v(this.topics[a]||[],function(a){u(a)&&a(b)})}},I=function(){function a(){var a=this;m(this,"ready",void 0);m(this,
"pendingCallbacks",void 0);m(this,"subReadyStateList",void 0);m(this,"isReady",function(){return a.dependsOnSubReadyState()?Ed(a.subReadyStateList,function(a){return a.isReady()}):a.ready});m(this,"setReady",function(){a.dependsOnSubReadyState()||a.ready||(a.ready=!0,a.callPendingCallbacks())});m(this,"waitFor",function(b){b=ka(b,function(a){return!!a});a.subReadyStateList=a.subReadyStateList.concat(b);a.isReady()?a.callPendingCallbacks():b.forEach(function(b){b.whenReady(a.whenSubReadyStateIsReady)})});
m(this,"whenSubReadyStateIsReady",function(){a.isReady()&&a.callPendingCallbacks()});this.ready=!1;this.pendingCallbacks=[];this.subReadyStateList=[]}var b=a.prototype;b.whenReady=function(a){this.isReady()?a():this.pendingCallbacks.push(a)};b.dependsOnSubReadyState=function(){return 0!==this.subReadyStateList.length};b.callPendingCallbacks=function(){this.pendingCallbacks.forEach(function(a){setTimeout(a,0)});this.pendingCallbacks=[]};return a}(),da;(function(a){a.PRE_PAGE_LOAD="PRE_PAGE_LOAD";a.POST_PAGE_LOAD=
"POST_PAGE_LOAD";a.AUX="AUX"})(da||(da={}));var O=new (function(){function a(a,b){var c=this;m(this,"requestBeaconAPI",void 0);m(this,"beaconRequestHandler",void 0);m(this,"requestsHistory",void 0);m(this,"noRequestPendingReadyState",void 0);m(this,"beaconApiResponseReadyState",void 0);m(this,"postPageLoadCallReadyState",void 0);m(this,"beaconFullyReadyState",void 0);m(this,"whenNoRequestsPending",function(a){c.noRequestPendingReadyState.whenReady(a)});m(this,"whenBeaconApiRequestCompleted",function(a){c.beaconApiResponseReadyState.whenReady(a)});
m(this,"whenPostPageLoadBeaconCallCompleted",function(a){c.postPageLoadCallReadyState.whenReady(a)});m(this,"whenBeaconFullyReady",function(a){c.beaconFullyReadyState.whenReady(a)});m(this,"sendBeaconRequest",function(a,b){var d=0===a.length,e={readyState:new I,requestedDomains:a,response:null,beaconCallType:b};c.hasFetchedAtLeastOnce()&&d?(c.requestsHistory.push(e),e.readyState.setReady()):c.requestBeaconAPI(a,b,function(b){b=y({requestedDomains:a},b);c.beaconRequestHandler(b);e.response=b;e.readyState.setReady()});
c.updateRequestsHistory(e);e.readyState.whenReady(function(){e.response&&z.publish("EVENTS__BEACON__REQUEST_COMPLETED",e);c.resolveReadyStatesOnRequestCompleted(e)});return e});this.requestBeaconAPI=a;this.beaconRequestHandler=b;this.requestsHistory=[];this.noRequestPendingReadyState=new I;this.noRequestPendingReadyState.setReady();this.beaconApiResponseReadyState=new I;this.postPageLoadCallReadyState=new I;this.beaconFullyReadyState=Fd(this.beaconApiResponseReadyState,this.postPageLoadCallReadyState)}
var b=a.prototype;b.updateRequestsHistory=function(a){this.requestsHistory.push(a);this.noRequestPendingReadyState.waitFor([a.readyState])};b.resolveReadyStatesOnRequestCompleted=function(a){a.response&&!this.beaconApiResponseReadyState.isReady()&&this.beaconApiResponseReadyState.setReady();a.beaconCallType===da.POST_PAGE_LOAD&&this.postPageLoadCallReadyState.setReady()};b.hasFetchedAtLeastOnce=function(){return 0!==this.requestsHistory.length};return a}())(function(a,b,c){a=JSON.stringify({pubcode:Za,
page:p.location.href,domains:a,link_swapping:Ka});a={headers:{"Content-type":"application/x-www-form-urlencoded"},data:U({data:a}),withCredentials:!0};var d=xa();"production"!==se&&(d._=b);gb.post(""+qe,d,c,a)},function(a){var b={};a.country&&(b.country=a.country.toUpperCase());a.country_state&&(b.countryState=a.country_state);a.guid&&""===n.cookie&&(b.cookie=a.guid);Ca(a.consent)&&(b.consent=a.consent);a.csp&&(b.cookieSyncString=a.csp);a.ts&&(b.lastBeaconTimestamp=a.ts);y(n,b);Dd(a.requestedDomains,
a.merchant_domains)}),ca;(ca||(ca={})).ANCHOR_CLICK_INTERCEPTOR="ANCHOR_CLICK_INTERCEPTOR";var pc={},ba;(function(a){a.LEFT_CLICK="LEFT_CLICK";a.MIDDLE_CLICK="MIDDLE_CLICK";a.OTHER_CLICK="OTHER_CLICK"})(ba||(ba={}));var pa;(function(a){a[a.LINK_SWAPPING=0]="LINK_SWAPPING";a[a.CONSENT=1]="CONSENT";a[a.INCENTIVE=2]="INCENTIVE";a[a.SKIMLINKS=3]="SKIMLINKS"})(pa||(pa={}));var Tc={}.hasOwnProperty;var Ab=0;var Bb=null;var Cb=0;var Pa=!1;var Qa={};var Me=function(a){Qa[a]=Qa[a]||0;Qa[a]++;return a+"_"+
Qa[a]};var Ne=function(a){var b;var c=b=null;if(-1!==a.indexOf(".")){a=a.split(".");var d=a[0];c=a[1]}else-1!==a.indexOf("[class=")?(a=a.split("[class="),d=a[0],c=a[1].split("]"),c=c[0]):-1!==a.indexOf("[class^=")?(a=a.split("[class^="),d=a[0],c=a[1].split("]"),c=c[0]):-1!==a.indexOf("[id*=")?(a=a.split("[id*="),d=a[0],b=a[1].split("]"),b=b[0]):d=a;return{tag:d,id:b,"class":c}};var ua=function(a,b){var c;var d=b.split(",");var e=0;for(c=d.length;e<c;e++){b=d[e];b=F(b);b=Ne(b);var f=!0;var l=(l="string"===
typeof a.className?a.className:"")||("function"===typeof a.getAttribute?a.getAttribute("class"):void 0)||"";var k=("function"===typeof a.getAttribute?a.getAttribute("id"):void 0)||"";!b.tag||a.nodeName&&a.nodeName.toLowerCase()===b.tag||(f=!1);b["class"]&&(!l||l!==b["class"]&&0!==l.indexOf(b["class"]))&&(f=!1);b.id&&(!k||k!==b.id&&-1===k.indexOf(b.id))&&(f=!1);if(f)return!0}return!1};var Uc=function(a,b){return ua(a,b)?[a]:oc(a.querySelectorAll(b))};var Oe=function(a,b){return 0<a.querySelectorAll(b).length};
var Db=function(a,b){return 0===b.length||ua(a,b.join(","))?!0:a.parentNode?Db(a.parentNode,b):!1};var Vc=function d(b,c){return 0===c.length?!1:ua(b,c.join(","))?!0:b.parentNode?d(b.parentNode,c):!1};var Pe=function(b){var c=b.offsetWidth;b=b.offsetHeight;return 468===c&&60===b||234===c&&60===b||728===c&&90===b||300===c&&250===b||250===c&&250===b||336===c&&280===b||160===c&&600===b||120===c&&600===b?!0:!1};var Qe=function(){var b=[];b.push("div.widget-content");b.push("div.googleAdText");b.push("div[id=ad]");
b.push("div[id=banner]");b.push("div[id=advertisement]");b.push("div[id=adv_container]");b.push("div.ad");b.push("div.banner");b.push("div.advertisement");b.push("div.ad_container");b.push("span.IL_AD");b.push("div[id=fave-ext-container]");b.push("span.skimlinks-unlinked");-1!==p.location.href.indexOf(".google.")?(b.push("td.gac_c"),b.push("table[id=mbEnd]"),b.push("div[id=mbEnd]"),b.push("span[id=taw]"),b.push("td.std"),b.push("div.std"),b.push("table.gssb_e"),b.push("div.c"),b.push("div[id=tads]")):
-1!==p.location.href.indexOf(".yahoo.")?(b.push("ul.spns,ul.reducepx-spnslist"),b.push("ul[class*=reducepx-spnslist]"),b.push("ul[id=east]")):-1!==p.location.href.indexOf(".aol.")?(b.push("div.sllLink"),b.push("div.n")):-1!==p.location.href.indexOf(".bing.")&&(b.push("div.sb_adsW"),b.push("div[id=sidebar]"),b.push("div.sb_adsWv2"),b.push("div.sb_adsNv2"),b.push("div[class*=sb_ads]"));return b};var Re=function(b){var c;var d={};var e=0;for(c=b.length;e<c;e++){var f=b[e];d[f]=!0}return d};var Se=function(){Ab=
0;z.publish("dom_changed")};var Te=function(b,c,d,e){var f,l,k;if((f=b.className||("function"===typeof b.getAttribute?b.getAttribute("class"):void 0)||"")&&("skimlinks-unlinked"===f||"skimwords-link"===f))return!1;if(0===d.length&&0===c.length)return x.traverse_node(b,!1,"","",e);if(0!==d.length){if(!Vc(b,d)){f=x.get_exclude_selector(d);d=x.get_exclude_selector([]);var h=f.selector;var g=f.needed;var n=d.selector;if(0===c.length||Db(b,c))return x.traverse_node(b,g,n,h,e);f=[];var m=0;for(k=c.length;m<
k;m++){d=c[m];var p=Uc(b,d);p.length?f.push(function(){var b;var c=[];var d=0;for(b=p.length;d<b;d++)l=p[d],c.push(x.traverse_node(l,g,n,h,e));return c}()):f.push(void 0)}return f}}else if(0!==c.length){if(Db(b,c))return x.traverse_node(b,!1,"","",e);k=[];f=0;for(m=c.length;f<m;f++)d=c[f],p=Uc(b,d),p.length?k.push(function(){var b;var c=[];var d=0;for(b=p.length;d<b;d++)l=p[d],c.push(x.traverse_node(l,!1,"","",e));return c}()):k.push(void 0);return k}};D(function(b){b=b.relatedNode||!1;if(!b||qa.send_in_progress||
g("stop_skimwords_ajax"))return!1;Bb&&clearTimeout(Bb);Ab++;1===Ab&&x.reset();Te(b,qa.settings.includes||[],qa.settings.excludes||[],qa.settings.read_onlys||[]);if(x.get_non_colliding_nodes()&&1<=Cb)return Bb=L(function(){Se()},1E3)});var x=function(){var b={};return{traverse:function(c,d,e,f){c=c||[];d=d||[];e=e||[];return b&&b.length&&!f?b:this.traverse_dom(c,d,e)},traverse_dom:function(c,d,e){var f,l;if(Pa)return b;Pa=!0;var k=this.get_exclude_selector(d);var h=this.get_exclude_selector([]);d=
k.selector;k=k.needed;h=h.selector;0===c.length&&c.push("body");c=c.concat(e);for(var g=0,m=c.length;g<m;g++){var n=c[g];n=sc(n);n=document.querySelectorAll(n);var p=f=0;for(l=n.length;f<l;p=++f)p=n[p],this.traverse_node(p,k,h,d,e)}return b},traverse_node:function(c,d,e,f,l){var k=[];var h=0;for(k.push({node:c,tagName:"",readOnly:!1,parent_id:null});h<k.length;)!(c=k[h].node)||Pe(c)||S(c,"noskimwords")||S(c,"noskim")||d&&""!==e&&ua(c,e)||(k[h].readOnly=!1,c.nodeName&&"#text"!==c.nodeName?(k[h].tagName=
c.nodeName,null!==k[h].parent_id&&(k[h].readOnly=k[k[h].parent_id].readOnly),k[h].readOnly||(d&&ua(c,f)?k[h].readOnly=!0:q(l,c.nodeName.toLowerCase())&&(k[h].readOnly=!0)),q(l,c.nodeName.toLowerCase())&&(k[h].readOnly=!0)):null!==k[h].parent_id&&(k[h].tagName=k[k[h].parent_id].tagName,k[h].readOnly=k[k[h].parent_id].readOnly),"msie"===n.detect.browser&&9>n.detect.version&&k[h].readOnly||(c.hasChildNodes()?k=this.add_child_nodes(k[h],h,k):this._add(c,!1,k[h].tagName,k[h].readOnly))),h++;return b},
is_traversed:function(){return Pa},is_good_tag:function(b){return Re("p body div span ul ol li table tbody td tr th tfoot col colgroup em strong big small blockquote cite b dl dfn dd dt ins form legend noframes pre noscript center font i article section main".split(" "))[b.nodeName.toLowerCase()]?!0:!1},is_html:function(b){return(b=F(b))&&"<"===b[0]},get_non_colliding_nodes:function(){var c;var d=b;var e={};Cb=0;for(c in d)Tc.call(d,c)&&(e[c]=d[c],Cb++);return e},get_as_hash_node_dict:function(){var c;
var d={};for(c in b){var e=b[c];K(b,c)&&(d[c]=e)}return d},get_as_pair_array:function(){var c;var d=[];for(c in b)Tc.call(b,c)&&d.push([c,b[c]]);return d},get_exclude_selector:function(b,d){var c,f,l;var k=[];if(!d){d=document.getElementsByTagName("body");if(!d.length)return{needed:!1,selector:""};d=d[0]}b=b.concat(Qe());var h=c=0;for(f=b.length;c<f;h=++c)b[h]=sc(b[h]);c=!1;f="";var g=0;for(l=b.length;g<l;g++)h=b[g],Oe(d,h)&&k.push(h);k.length&&(c=!0,f=k.join(",").replace("class=","class^="));return{needed:c,
selector:f}},length:function(){return Object.keys(b).length},reset:function(){b=[];return Pa=!1},add_child_nodes:function(b,d,e){var c,l;var k=b.node.childNodes;var h=0;for(l=k.length;h<l;h++)(c=k[h])&&c.nodeName&&!this._add(c,!1,b.tagName,b.readOnly)&&this.is_good_tag(c)&&e.push({node:c,tagName:b.tagName,readOnly:b.readOnly,parent_id:d});return e},add_node:function(b,d){return this._add(b,d)},_add:function(c,d,e,f){var l=null;"#text"===c.nodeName&&(l=F(c.nodeValue));d=d||!1;if("msie"===n.detect.browser&&
9>n.detect.version&&f)return!1;if("msie"!==n.detect.browser||9<=n.detect.version)try{c.meta={ElementTag:e,ReadOnly:f}}catch(k){}if(l&&!this.is_html(l)&&3<=l.length){if(d&&"-1"===d)return!1;d=this._skim_id_hash(l,d);if(!d)return!1;b[d]=c}return l?!0:!1},_skim_id_hash:function(b){if(!b)return"";var c=F(b.replace(/\s+/g," ")).length;b=b.replace(/[:\s]*/g,"");c=c+":"+b.substring(0,20);return c=Me(c)}}}();var Qd=function(b,c,d){if(ha)return!1;var e=(b.data?b.data:b.childNodes[0].data).replace(c.repl_regex,
c.replacement);var f=document.createElement("span");c=document.createDocumentFragment();f.innerHTML=e;if("msie"===n.detect.browser&&9>n.detect.version){e=b.previousSibling;var l=/^\s/;e&&e.nodeValue&&e.nodeValue.length&&l.test(e.nodeValue[e.nodeValue.length-1])&&(e.nodeValue+=" ");(e=b.nextSibling)&&e.nodeValue&&e.nodeValue.length&&l.test(e.nodeValue[0])&&(e.nodeValue=" "+e.nodeValue)}for(;f.firstChild;)"#text"===f.firstChild.nodeName?(e=c.appendChild(f.firstChild),x.add_node(e)):(e=c.appendChild(f.firstChild),
null===e||d||Hb(e,!0));if(d=b.parentNode)return d.replaceChild(c,b)};var w={campaign_ids:[],loading_started:(new Date).getTime(),linksImpressions:{skimlinks:{count:0,urls:{}},skimwords:{count:0,urls:{}},unlinked:{count:0,urls:{}}},awaitedModules:[]},Pd=new I,bd=[".noskim",".noskimwords",".noskimw"];var Rd=function(b){qb(b,"click",wc);Oc||qb(b,"contextmenu",wc);return Hb(b,!1)};var Ue=function(b,c,d,e){var f=Le(b);c=pb(c);f="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/:\\?])?("+f+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/:\\?])*(?:[\\s]+|$)";
b=Ub(pb(b));c='$1$2<a href="'+c+'" class="'+e+'"  data-skimwords-word="'+b+'"  data-skim-creative="'+d+'" title="">$3$4</a>$5$6';d=f.replace(/\?:/g,"");return{search_regex:new RegExp(f,"i"),repl_regex:new RegExp(d,"i"),repl_text:c}};var $c=function(b,c){var d,e,f;if(!b||Vc(b,["span.skimlinks-unlinked"]))return[[],[]];var l=b.data;var k=[];var h=[];for(e=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^[\]\s]*\b|$/gi;d=e.exec(l);){var g=d[0];if("link.phrase"!==g){var m=d.index;
if(0<F(g).length&&-1===g.indexOf("/.")&&-1===g.indexOf("...")){var p=g;0!==g.indexOf("http")&&0!==g.indexOf("//")&&(p="msie"===n.detect.browser&&6>=n.detect.version?"http://"+g:"//"+g);d=B(p);var r=cd({OriginalPhrase:""+g,Url:p,Title:"",ActionType:2,GroupId:0,Unlinked:!0});(f=Ue(""+g,p,Ma.creative,"skimlinks-unlinked"))&&h.push({start:m,text:""+pb(g),domain:d,repl_regex:f.repl_regex,replacement:f.repl_text,regex:f.search_regex,phrase:r,link:p});k.push(d)}else break}}if(h.length){var q=c;p="skimlinks-unlinked";
var v;g=document.createDocumentFragment();var t=0;d=[];m=b.nodeValue;e=[];l=b.parentNode;p||(p="skimwords-potential");q||(q="-1");if(l){r=0;for(v=h.length;r<v;r++){var u=h[r];var w=document.createElement("span");w.className=p;f=document.createTextNode(m.substring(t,u.start));g.appendChild(f);w.innerHTML=u.text;g.appendChild(w);t={};t.node=w;t.match=u;C(t,"occurrence",u.target_occurrence);d.push(t);t=u.start+u.text.length;e.push(f);x.add_node(f,q)}h=document.createTextNode(m.substring(t));e.push(h);
g.appendChild(h);x.add_node(h,q);l.replaceChild(g,b)}q=[d,e];h=q[0];q=q[1];g=0;for(e=h.length;g<e;g++)l=h[g],Ma.url_spans.push(l)}q||(q=[]);return[k,q]};var ad=function(b){var c;if(r.exclude.length){var d=r.exclude;var e=0;for(c=d.length;e<c;e++){var f=d[e];if(f===b)return!1}}if(r.include.length){d=r.include;e=0;for(c=d.length;e<c;e++)if(f=d[e],f===b)return!0;return!1}return!0};var Td={async:!0,onError:function(){},onLoad:function(){}},Zd=["skimlinks_included_ids","skimlinks_byrel","skimlinks_exrel",
"skimlinks_included_classes"],Wc=function(){function b(){m(this,"SERVICES",b.SERVICES);m(this,"getService",nb);m(this,"trackEvent",nc);z.on("skim_js_init",this.onInit.bind(this));z.on("skim_js_start",this.onStart.bind(this));O.whenBeaconFullyReady(this.whenBeaconFullyReady.bind(this))}var c=b.prototype;c.onInit=function(){};c.onStart=function(){};c.whenBeaconFullyReady=function(){};c.publishEvent=function(b,c){z.publish(b,c)};c.onEvent=function(b,c){z.on(b,c)};c.registerClickInterceptor=function(b,
c){nb(ca.ANCHOR_CLICK_INTERCEPTOR).registerInterceptor(b,c)};return b}();m(Wc,"SERVICES",ca);var Xc=new I,Ve=function(b){function c(){var c=arguments.length;for(var d=Array(c),l=0;l<c;l++)d[l]=arguments[l];c=b.call.apply(b,[this].concat(d))||this;m(Y(c),"excludedDomains",void 0);m(Y(c),"linkSwappingDomains",[]);m(Y(c),"otherMerchantDomains",[]);m(Y(c),"swappedAnchorsInfo",[]);m(Y(c),"nonSwappedAnchorsInfo",[]);m(Y(c),"onAnchorClick",function(b){var c=b.anchor.getAttribute("data-skimlinks-link-swapping-match-id");
if(!c)return!1;b.setAnchorClickInterceptorTarget(pa.SKIMLINKS);b.setSourceApp(15);b.setLinkSwappingMatchId(c);return!1});return c}qd(c,b);var d=c.prototype;d.onInit=function(){this.excludedDomains=g("skimlinks_excluded_link_swapping_domains",[]);this.onEvent("EVENTS__BEACON__REQUEST_COMPLETED",this.onBeaconRequestCompleted.bind(this))};d.onStart=function(){this.registerClickInterceptor(this.onAnchorClick,pa.LINK_SWAPPING)};d.onBeaconRequestCompleted=function(b){var c=this;b=b.response;b.link_swapping_domains.forEach(function(b){q(c.linkSwappingDomains,
b)||c.linkSwappingDomains.push(b)});b.merchant_domains.forEach(function(b){q(c.linkSwappingDomains,b)||q(c.otherMerchantDomains,b)||c.otherMerchantDomains.push(b)})};d.whenBeaconFullyReady=function(){var b=this,c=this.getSwappableAnchors();if(c.length){var d=this.sendLinkSwappingApiRequest(c);d.readyState.whenReady(function(){var e=d.response;e&&0!==Object.keys(e).length&&(b.registerLinkSwappingDomainsAsAffiliate(e),b.applyLinkSwapping(c,e),b.sendLinkSwappingTracking(),b.sendLinkNonSwappedTracking());
b.onLinkSwappingProcessDone()})}else this.onLinkSwappingProcessDone()};d.registerLinkSwappingDomainsAsAffiliate=function(b){v(b,function(b){v(b,function(b){b=b.matching_domain;!1!==r.aff_domains[b]&&(r.aff_domains[b]=!0)})})};d.getSwappableAnchors=function(){var b=this,c=na();return ka(c,function(c){if("false"===(null==c?void 0:c.getAttribute("data-skimlinks-link-swapping")))return!1;var d=B(c.href);if(N(d)){var e=La.createFromUrl(c.href);e&&(d=e.getTargetDomain())}return q(b.excludedDomains,d)||
!q(b.linkSwappingDomains,d)&&!q(b.otherMerchantDomains,d)||jb(c)?!1:!0})};d.sendLinkSwappingApiRequest=function(b){b=Ra(b.map(Dc));var c={readyState:new I,response:null};ce(b,function(b){c.response=b;c.readyState.setReady()});return c};d.applyLinkSwapping=function(b,c){var d=this;v(b,function(b){var e=Dc(b),f=d.getBestLinkSwappingMatch(c[e]);e=d.isBlockedByMerchantNameOnPage(f,e);f&&!e?d.swapAnchorLink(b,f):e&&d.nonSwappedAnchorsInfo.push({originalHref:b.href,anchor:b,match:f,reason:"merchant_name_on_page"})})};
d.getBestLinkSwappingMatch=function(b){return b?b.filter(function(b){return"404"===b.reason&&yb||"product_match"===b.reason&&zb})[0]:null};d.isBlockedByMerchantNameOnPage=function(b,c){return Qc&&b&&B(c)!==b.matching_domain?ib(b.original_merchant_names,function(b){var c;return-1!==(null==(c=document.body)?void 0:c.innerText.toLowerCase().indexOf(b.toLowerCase()))}):!1};d.swapAnchorLink=function(b,c){var d=b.href;b.setAttribute("data-skimlinks-link-swapping-original",d);b.setAttribute("data-skimlinks-link-swapping-match-id",
c.id.toString());if(fc(d)){var e=La.createFromUrl(b.href);e.updateWaypointParams({url:encodeURIComponent(c.matching_link),xs:15,ls:c.id});b.href=e.getWaypointUrl()}else b.href=c.matching_link;this.swappedAnchorsInfo.push({originalHref:d,anchor:b,match:c})};d.sendLinkSwappingTracking=function(){var b=this.swappedAnchorsInfo.map(function(b){return{match:b.match,originalHref:b.originalHref}});this.trackEvent("link_swapping__swapped_links",{number_of_links_swapped:this.swappedAnchorsInfo.length,swappedAnchorsInfo:JSON.stringify(b)})};
d.sendLinkNonSwappedTracking=function(){var b=this.nonSwappedAnchorsInfo.map(function(b){return{match:b.match,originalHref:b.originalHref,reason:b.reason}});0<this.nonSwappedAnchorsInfo.length&&this.trackEvent("link_swapping__not_swapped",{number_of_links_non_swapped:this.nonSwappedAnchorsInfo.length,nonSwappedAnchorsInfo:JSON.stringify(b)})};d.onLinkSwappingProcessDone=function(){Xc.isReady()||Xc.setReady()};return c}(Wc),tb=!1,ea=!1,ra=null,sa=null,oe={detect:function(b){a:{try{var c=navigator.userAgent.toLowerCase();
if(-1===c.indexOf("firefox")&&-1===c.indexOf("chrome")){ea=!0;tb=!1;break a}}catch(d){}c=""+11*Math.random();ra=new Image;ra.onload=Fc;ra.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,"1").replace(/\*/,c);sa=new Image;sa.onload=Fc;sa.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,"2").replace(/\*/,c)}Ec(b,250)}};new I;var he={},Yc=Tb([!!Nc&&"mouseup","click"]),We=["auxclick","contextmenu","touchstart"],Xe=function(){function b(b,c){m(this,"type",void 0);m(this,"anchor",void 0);
m(this,"affiliationType",void 0);m(this,"nativeEvent",void 0);m(this,"clientClickId",void 0);m(this,"targetedInterceptor",void 0);var d=xd(b);this.type=this.getInternalClickType(c);this.anchor=b;this.affiliationType=d;this.nativeEvent=c;this.clientClickId=$a();this.targetedInterceptor=null}var c=b.prototype;c.setAnchorClickInterceptorTarget=function(b){this.targetedInterceptor=b};c.setSourceApp=function(b){var c=this.anchor;H(c).sourceApp=b;Ha(c)};c.setLinkSwappingMatchId=function(b){var c=this.anchor;
H(c).linkSwappingMatchId=b;Ha(c)};c.getInternalClickType=function(b){return q(Yc,b.type)&&0===b.button?ba.LEFT_CLICK:"auxclick"!==b.type&&"click"!==b.type||1!==b.button?ba.OTHER_CLICK:ba.MIDDLE_CLICK};return b}(),ke=function(){function b(){var b=this;m(this,"interceptors",void 0);m(this,"onClick",function(c,d){var e=Ib(c);e&&(e.skimlinksOriginalHref&&e.skimlinksRestoreSwappedLink(),e=new Xe(e,c),b.dispatchAnchorClick(e,d))});m(this,"registerInterceptor",function(c,d){if(!u(c))throw Error("InterceptorHandler should be a function");
if(G(d))throw Error("Missing priority for click interceptor");b.interceptors.push({handler:c,priority:d});b.interceptors.sort(function(b,c){return b.priority-c.priority})});m(this,"triggerLeftClickFromMouseEvent",function(c,d){var e=b.findInterceptorsWithPriority(d);if(G(d))b.onClick(c);else if(e.length)b.onClick(c,e)});this.interceptors=[];this.initGlobalClickHandler()}var c=b.prototype;c.initGlobalClickHandler=function(){Hc(E,Yc,this.onClick,!0);Hc(E,We,this.onClick,!0)};c.dispatchAnchorClick=function(b,
c){var d=this;(c||this.interceptors).some(function(c){var e=c.handler;return d.isTargetedInterceptor(c,b)?e(b):!1})};c.findInterceptorsWithPriority=function(b){return ka(this.interceptors,function(c){return c.priority===b})};c.isTargetedInterceptor=function(b,c){var d=c.targetedInterceptor===b.priority;return!c.targetedInterceptor||d};return b}(),ta=D(function(){tc(da.POST_PAGE_LOAD);document.removeEventListener("DOMContentLoaded",ta);document.removeEventListener("load",ta)}),me={skimlinks:!1,skimwords:!1,
unlinked:!1,audience:!1,GDPRConsent:!1,incentivePopup:!1};Vb&&D(function(){z.on("skim_js_init",Jd);z.on("skim_js_init",Nd);O.whenPostPageLoadBeaconCallCompleted(Vd);z.on("skim_js_init",ae);z.on("skim_js_start",be);Ka&&new Ve;le()})()})();
